### ISSUE TITLE
Search functionality error handling

### ISSUE THREAD

**Issue by lcampolo** [bert93/DogAtTheTurn#1]
It looks like you have the same result of handling an error, versus not finding a review with the search string, which is to redirect to the /404 route error page. 

You probably want to handle this differently, because you want to indicate to the user that a server error occured versus they just typed a search in that resulted in no reviews. So when there are none, i'd display a page that just says 'no reviews found with search text <TEXT>' or something

**Comment by bert93** [comment]
I updated the route so you're redirected to a different page with a more descriptive message.
